language: crystal

crystal:
    - latest
    - nightly

install:
  - shards install

script:
  - crystal spec
  - crystal tool format --check
  - crystal docs

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  project_name: crystal-lapper
  on:
    branch: master
  local_dir: docs